config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web' if Rails.env.development?

Rails.application.routes.draw do
  scope module: :web do
    resources :repositories, only: %i[index show new create] do
      resources :checks, only: %i[create show], module: :repositories
    end

    root 'welcome#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete '/logout', to: 'auth#logout'
  end

  namespace :api do
    resources :checks, only: [:create]
  end

  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  ACCEPTED_LANGUAGES = %w[Ruby JavaScript].freeze

  extend Enumerize

  belongs_to :user, touch: true
  has_many :checks, dependent: :destroy

  validates :github_id, presence: true
  enumerize :language, in: ACCEPTED_LANGUAGES
end

app/models/repository/check.rb
# frozen_string_literal: true

class Repository::Check < ApplicationRecord
  include AASM

  belongs_to :repository
  has_many :offenses, dependent: :destroy

  aasm column: :aasm_state do
    state :created, initial: true
    state :checking, :finished, :failed

    event :start do
      transitions from: :created, to: :checking
    end

    event :finish do
      transitions from: :checking, to: :finished
    end

    event :fail do
      transitions from: %i[created checking], to: :failed
    end
  end
end

app/models/repository/offense.rb
# frozen_string_literal: true

class Repository::Offense < ApplicationRecord
  belongs_to :check, class_name: 'Repository::Check', counter_cache: :offenses_count
end

app/controllers/web/repositories/checks_controller.rb
# frozen_string_literal: true

class Web::Repositories::ChecksController < Web::ApplicationController
  before_action :authenticate_user!

  def show
    @check = Repository::Check.find(params[:id])
    authorize @check
  end

  def create
    @repository = Repository.find(params[:repository_id])
    @check = @repository.checks.create
    authorize @check
    CheckRepositoryJob.perform_later(@repository, @check)
    redirect_to repository_url(@repository), notice: t('.success')
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

require 'octokit'

module Web
  class RepositoriesController < Web::ApplicationController
    before_action :authenticate_user!

    def index
      @repositories = current_user.repositories.order(created_at: :desc)
    end

    def show
      @repository = Repository.find(params[:id])
      authorize @repository
    end

    def new
      authorize Repository
      @repository = current_user.repositories.build
      @github_repos = fetch_permitted_repos_from_github
    end

    def create
      authorize Repository
      @repository = find_or_initialize_repository
      @client = create_client
      if update_repository
        CreateChecksHookService.new.run(@repository, @client)
        redirect_to repositories_path, notice: t('.success')
      else
        flash.now[:alert] = t('.failure')
        render :new, status: :unprocessable_entity
      end
    end

    private

    def repository_params
      params.require(:repository).permit(:github_id)
    end

    def fetch_permitted_repos_from_github
      client = create_client
      Rails.cache.fetch("#{current_user.cache_key_with_version}/repos", expires_in: 10.minutes) do
        client.repos.select { |repo| Repository::ACCEPTED_LANGUAGES.include? repo[:language] }
      end
    end

    def find_or_initialize_repository
      current_user.repositories.find_or_initialize_by(repository_params)
    end

    def update_repository
      unless @repository.github_id
        @repository.errors.add(:github_id, :blank)
        return false
      end

      repository_data = RepositoryDataBuilderService.new.build(@repository.github_id, @client)
      @repository.update(repository_data)
    end

    def create_client
      ApplicationContainer[:octokit_client].new(access_token: current_user.token,
                                                auto_paginate: true)
    end
  end
end

app/helpers/web/repositories/checks_helper.rb
# frozen_string_literal: true

module Web::Repositories::ChecksHelper
  def human_attribute_name_passed(check)
    Repository::Check.human_attribute_name("passed/#{check.passed}")
  end

  def github_commit_url(repository, check)
    "#{repository.clone_url&.delete_suffix('.git')}/commit/#{check.commit_id}"
  end
end

app/helpers/web/repositories_helper.rb
# frozen_string_literal: true

module Web
  module RepositoriesHelper
  end
end

app/views/web/repositories/_form.html.slim
= simple_form_for repository do |f|
  div
    = f.input :github_id,
      collection: @github_repos,
      required: true,
      label: t('.repo_label')
  div
    = f.button :submit, t('.add_repo')

app/views/web/repositories/_repository.html.slim
h1.mb-4 = repository.full_name

= button_to t('.check'),
  repository_checks_path(@repository),
  class: 'btn btn-primary mb-4'

p
  strong.me-2
    = t('.name')
  = repository.full_name
p
  strong.me-2
    = t('.language')
  = repository.language
p
  strong.me-2
    = t('.created_at')
  = l(repository.created_at, format: :long)
p
  strong.me-2
    = t('.updated_at')
  = l(repository.updated_at, format: :long)

hr

= render 'web/repositories/checks/list_of_checks', repository: repository if repository.checks.any?

app/views/web/repositories/index.html.slim
h1
  = t('.title')
= link_to t('.add'), new_repository_path, class: 'btn btn-primary'

table.table.table-striped.table-hover.mt-4
  thead
    tr
      th{ scope = 'col' } = t('.repository_title')
      th{ scope = 'col' } = t('.language')
      th{ scope = 'col' } = t('.last_check_status')

  tbody
    - @repositories.each do |repository|
      tr
        td = link_to repository.full_name, repository
        td = repository.language
        td
          - if repository.checks.any?
            = human_attribute_name_passed(repository.checks.last)
          - else
            = t('.no_checks_yet')

app/views/web/repositories/new.html.slim
h1 = t('.new_repository')
= render 'form', repository: @repository
br
div
  = link_to t('.back_to_repositories'), repositories_path

app/views/web/repositories/show.html.slim
= render @repository