config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web' if Rails.env.development?

Rails.application.routes.draw do
  scope module: :web do
    resources :repositories, only: %i[index show new create] do
      resources :checks, only: %i[create show], module: :repositories
    end

    root 'welcome#index'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    delete '/logout', to: 'auth#logout'
  end

  namespace :api do
    resources :checks, only: [:create]
  end

  mount Sidekiq::Web => '/sidekiq' if Rails.env.development?
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  ACCEPTED_LANGUAGES = %w[Ruby JavaScript].freeze

  extend Enumerize

  belongs_to :user, touch: true
  has_many :checks, dependent: :destroy

  validates :github_id, presence: true
  enumerize :language, in: ACCEPTED_LANGUAGES
end

app/models/repository/check.rb
# frozen_string_literal: true

class Repository::Check < ApplicationRecord
  include AASM

  belongs_to :repository
  has_many :offenses, dependent: :destroy

  aasm column: :aasm_state do
    state :created, initial: true
    state :checking, :finished, :failed

    event :start do
      transitions from: :created, to: :checking
    end

    event :finish do
      transitions from: :checking, to: :finished
    end

    event :fail do
      transitions from: %i[created checking], to: :failed
    end
  end
end

app/models/repository/offense.rb
# frozen_string_literal: true

class Repository::Offense < ApplicationRecord
  belongs_to :check, class_name: 'Repository::Check', counter_cache: :offenses_count
end

app/controllers/api/checks_controller.rb
# frozen_string_literal: true

class Api::ChecksController < Api::ApplicationController
  WEBHOOK_GITHUB_EVENT = 'push'

  def create
    return head :unauthorized unless valid_signature?
    return head :unprocessable_entity unless valid_github_event?

    repository = find_repository
    return head :not_found unless repository

    check = repository.checks.create
    process_check_job(repository, check)
  end

  private

  def valid_signature?
    return true unless request.env['HTTP_X_HUB_SIGNATURE_256']

    secret = Rails.application.credentials.webhook_secret_github
    digest = OpenSSL::HMAC.hexdigest(OpenSSL::Digest.new('sha256'), secret, request.raw_post)
    signature = "sha256=#{digest}"
    Rack::Utils.secure_compare(signature, request.env['HTTP_X_HUB_SIGNATURE_256'])
  end

  def valid_github_event?
    github_event_header = request.headers['X-GitHub-Event']
    return true unless github_event_header

    github_event_header == WEBHOOK_GITHUB_EVENT
  end

  def find_repository
    Repository.find_by(github_id: params.dig(:repository, :id))
  end

  def process_check_job(repository, check)
    if CheckRepositoryJob.perform_later(repository, check)
      head :ok
    else
      head :internal_server_error
    end
  end
end

app/controllers/web/repositories/checks_controller.rb
# frozen_string_literal: true

class Web::Repositories::ChecksController < Web::ApplicationController
  before_action :authenticate_user!

  def show
    @check = Repository::Check.find(params[:id])
    authorize @check
  end

  def create
    @repository = Repository.find(params[:repository_id])
    @check = @repository.checks.create
    authorize @check
    CheckRepositoryJob.perform_later(@repository, @check)
    redirect_to repository_url(@repository), notice: t('.success')
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

require 'octokit'

module Web
  class RepositoriesController < Web::ApplicationController
    before_action :authenticate_user!

    def index
      @repositories = current_user.repositories.order(created_at: :desc)
    end

    def show
      @repository = Repository.find(params[:id])
      authorize @repository
    end

    def new
      authorize Repository
      @repository = current_user.repositories.build
      @github_repos = fetch_permitted_repos_from_github
    end

    def create
      authorize Repository
      @repository = find_or_initialize_repository
      @client = create_client
      if update_repository
        CreateChecksHookService.new.run(@repository, @client)
        redirect_to repositories_path, notice: t('.success')
      else
        flash.now[:alert] = t('.failure')
        render :new, status: :unprocessable_entity
      end
    end

    private

    def repository_params
      params.require(:repository).permit(:github_id)
    end

    def fetch_permitted_repos_from_github
      client = create_client
      Rails.cache.fetch("#{current_user.cache_key_with_version}/repos", expires_in: 10.minutes) do
        client.repos.select { |repo| Repository::ACCEPTED_LANGUAGES.include? repo[:language] }
      end
    end

    def find_or_initialize_repository
      current_user.repositories.find_or_initialize_by(repository_params)
    end

    def update_repository
      unless @repository.github_id
        @repository.errors.add(:github_id, :blank)
        return false
      end

      repository_data = RepositoryDataBuilderService.new.build(@repository.github_id, @client)
      @repository.update(repository_data)
    end

    def create_client
      ApplicationContainer[:octokit_client].new(access_token: current_user.token,
                                                auto_paginate: true)
    end
  end
end

app/helpers/web/repositories/checks_helper.rb
# frozen_string_literal: true

module Web::Repositories::ChecksHelper
  def human_attribute_name_passed(check)
    Repository::Check.human_attribute_name("passed/#{check.passed}")
  end

  def github_commit_url(repository, check)
    "#{repository.clone_url&.delete_suffix('.git')}/commit/#{check.commit_id}"
  end
end

app/helpers/web/repositories_helper.rb
# frozen_string_literal: true

module Web
  module RepositoriesHelper
  end
end

app/views/web/repositories/checks/_list_of_checks.html.slim
table.table.table-striped
  thead
    tr
      th{ scope = 'col' }
      th{ scope = 'col' } = t('.aasm_state')
      th{ scope = 'col' } = t('.commit_id')
      th{ scope = 'col' } = t('.check_passed')
      th{ scope = 'col' } = t('.created_at')

  tbody
    - repository.checks.order(created_at: :desc).each do |check|
      tr
        td = link_to check.id, repository_check_path(repository, check)
        td = check.aasm.human_state
        td = link_to check.commit_id, github_commit_url(@repository, check) if check.commit_id
        td = human_attribute_name_passed(check)
        td = l(repository.created_at, format: :short)

app/views/web/repositories/checks/_offenses.html.slim
table.table.table-hover.mb-5
  thead
    tr
      th{ scope = 'col' } = t('.message')
      th{ scope = 'col' } = t('.rule')
      th{ scope = 'col' } = t('.string_and_symbol')
  tbody
    - offenses.each do |offense|
      tr
        td{ colspan = '3' } = link_to offense.path, offense.github_url
      tr
        td = offense.message
        td = offense.rule_id
        td = offense.coords

app/views/web/repositories/checks/show.html.slim
= link_to t('.to_repository'), @check.repository, class: 'btn btn-primary mb-4'
h1 = "#{t('.checking')} # #{@check.commit_id}"

table.table
  tbody
    tr
      td = t('.created_at')
      td = l(@check.created_at, format: :long)
    tr
      td = t('.state')
      td = @check.aasm.human_state
    tr
      td = t('.check_passed')
      td = human_attribute_name_passed(@check)
    tr
      td = t('.offenses_count')
      td = @check.offenses_count
    tr
      td = t('.commit_id')
      td = @check.commit_id

= render 'offenses', offenses: @check.offenses if @check.offenses.any?